In [1]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 102C-9CE7

 Directory of C:\Users\Gaurab\Workspace\my_files

12-02-2021  08:44    <DIR>          .
12-02-2021  08:44    <DIR>          ..
12-02-2021  08:42    <DIR>          .ipynb_checkpoints
21-12-2020  23:06            16,460 ANOVA.ipynb
10-02-2021  09:29             2,928 BagofWords.py
11-02-2021  09:45            14,672 Cosine_Similarity.ipynb
13-01-2021  13:20           889,375 DT_RF_Classification_analysis.ipynb
28-12-2020  12:55         1,250,841 EDA_COVID.ipynb
10-12-2020  13:28           749,601 EDA_HouseData.ipynb
02-01-2021  13:33           147,136 EDA_Titanic.ipynb
18-12-2020  15:02             3,975 HypothesisTesting.ipynb
19-12-2020  18:47            50,832 HypothesisTesting_cereals.ipynb
23-11-2020  12:46         1,085,001 Image analysis.ipynb
08-01-2021  13:09           309,996 K-Nearest Neighbors (KNN).ipynb
15-01-2021  13:18           693,069 Linear_Regression.ipynb
15-01-2021  12:16         1,337,906 Logistic

In [1]:
import numpy as np
import pandas as pd
import string
import re
from nltk.corpus import stopwords

In [2]:
pos_df = pd.read_csv('../DataSet/Netflix_data/pos.txt', sep='\n', encoding='latin-1', header=None)
pos_df

0
0     the rock is destined to be the 21st century's ...
1     the gorgeously elaborate continuation of " the...
2                        effective but too-tepid biopic
3     if you sometimes like to go to the movies to h...
4     emerges as something rare , an issue movie tha...
...                                                 ...
5326  both exuberantly romantic and serenely melanch...
5327  mazel tov to a film about a family's joyous li...
5328  standing in the shadows of motown is the best ...
5329  it's nice to see piscopo again after all these...
5330  provides a porthole into that noble , tremblin...

[5331 rows x 1 columns]

In [3]:
pos_df['Mood'] = 1
pos_df = pos_df.rename(columns={0:'Review'})
pos_df

Review  Mood
0     the rock is destined to be the 21st century's ...     1
1     the gorgeously elaborate continuation of " the...     1
2                        effective but too-tepid biopic     1
3     if you sometimes like to go to the movies to h...     1
4     emerges as something rare , an issue movie tha...     1
...                                                 ...   ...
5326  both exuberantly romantic and serenely melanch...     1
5327  mazel tov to a film about a family's joyous li...     1
5328  standing in the shadows of motown is the best ...     1
5329  it's nice to see piscopo again after all these...     1
5330  provides a porthole into that noble , tremblin...     1

[5331 rows x 2 columns]

In [4]:
neg_df = pd.read_csv('../DataSet/Netflix_data/negative.txt', sep='\n', encoding='latin-1', header=None)
neg_df

0
0                      simplistic , silly and tedious. 
1     it's so laddish and juvenile , only teenage bo...
2     exploitative and largely devoid of the depth o...
3     [garbus] discards the potential for pathologic...
4     a visually flashy but narratively opaque and e...
...                                                 ...
5326  a terrible movie that some people will neverth...
5327  there are many definitions of 'time waster' bu...
5328  as it stands , crocodile hunter has the hurrie...
5329  the thing looks like a made-for-home-video qui...
5330  enigma is well-made , but it's just too dry an...

[5331 rows x 1 columns]

In [5]:
neg_df['Mood'] = 0
neg_df = neg_df.rename(columns={0:'Review'})
neg_df

Review  Mood
0                      simplistic , silly and tedious.      0
1     it's so laddish and juvenile , only teenage bo...     0
2     exploitative and largely devoid of the depth o...     0
3     [garbus] discards the potential for pathologic...     0
4     a visually flashy but narratively opaque and e...     0
...                                                 ...   ...
5326  a terrible movie that some people will neverth...     0
5327  there are many definitions of 'time waster' bu...     0
5328  as it stands , crocodile hunter has the hurrie...     0
5329  the thing looks like a made-for-home-video qui...     0
5330  enigma is well-made , but it's just too dry an...     0

[5331 rows x 2 columns]

### Text Anlytics(Cleaning the data):
1. lowercase
2. puntuation removal
3. Stopwords removal
4. Remove numbers, special characters, links, etc.

In [6]:
pos_df.loc[:, 'Review'] = pos_df.loc[:, 'Review'].apply(lambda x: x.lower())
pos_df.loc[:, 'Review'] = pos_df.loc[:, 'Review'].apply(lambda x: x.translate(str.maketrans(dict.fromkeys(string.punctuation))))
pos_df.loc[:, 'Review'] = pos_df.loc[:, 'Review'].apply(lambda x: " ".join([i for i in x.split() if i not in stopwords.words('english')]))
pos_df.loc[:, 'Review'] = pos_df.loc[:, 'Review'].apply(lambda x: re.sub(r'\d', '', x))
pos_df.head()

Review  Mood
0  rock destined st centurys new conan hes going ...     1
1  gorgeously elaborate continuation lord rings t...     1
2                          effective tootepid biopic     1
3  sometimes like go movies fun wasabi good place...     1
4  emerges something rare issue movie thats hones...     1

In [7]:
neg_df.loc[:, 'Review'] = neg_df.loc[:, 'Review'].apply(lambda x: x.lower())
neg_df.loc[:, 'Review'] = neg_df.loc[:, 'Review'].apply(lambda x: x.translate(str.maketrans(dict.fromkeys(string.punctuation))))
neg_df.loc[:, 'Review'] = neg_df.loc[:, 'Review'].apply(lambda x: " ".join([i for i in x.split() if i not in stopwords.words('english')]))
neg_df.loc[:, 'Review'] = neg_df.loc[:, 'Review'].apply(lambda x: re.sub(r'\d', '', x))
neg_df.head()

Review  Mood
0                           simplistic silly tedious     0
1  laddish juvenile teenage boys could possibly f...     0
2  exploitative largely devoid depth sophisticati...     0
3  garbus discards potential pathological study e...     0
4  visually flashy narratively opaque emotionally...     0

### Concatenate the dataset

In [8]:
df = pd.concat([pos_df, neg_df], axis=0).reset_index()
df

index                                             Review  Mood
0          0  rock destined st centurys new conan hes going ...     1
1          1  gorgeously elaborate continuation lord rings t...     1
2          2                          effective tootepid biopic     1
3          3  sometimes like go movies fun wasabi good place...     1
4          4  emerges something rare issue movie thats hones...     1
...      ...                                                ...   ...
10657   5326     terrible movie people nevertheless find moving     0
10658   5327  many definitions time waster movie must surely...     0
10659   5328  stands crocodile hunter hurried badly cobbled ...     0
10660   5329          thing looks like madeforhomevideo quickie     0
10661   5330                         enigma wellmade dry placid     0

[10662 rows x 3 columns]

### Train Test Split

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(df['Review'].values, df['Mood'].values, test_size = 0.2, random_state = 101)

In [12]:
train_data = pd.DataFrame({'Review': X_train, 'Mood': Y_train})
test_data = pd.DataFrame({'Review': X_test, 'Mood': Y_test})

### Converting text to Vector form

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

In [14]:
train_vectors = vectorizer.fit_transform(train_data['Review'])
test_vectors = vectorizer.transform(test_data['Review'])

In [15]:
train_vectors.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
test_vectors

<2133x8382 sparse matrix of type '<class 'numpy.float64'>'
	with 22370 stored elements in Compressed Sparse Row format>

In [24]:
vectorizer.get_feature_names()

['aan',
 'abandon',
 'abandons',
 'abbas',
 'abbass',
 'abbott',
 'abbreviated',
 'abdul',
 'abel',
 'ability',
 'able',
 'abomination',
 'aborted',
 'aboveaverage',
 'abrasive',
 'abrupt',
 'abruptly',
 'absence',
 'absolute',
 'absolutely',
 'absorbing',
 'absurd',
 'absurdist',
 'absurdity',
 'absurdly',
 'abundance',
 'abundantly',
 'abuse',
 'abusers',
 'abuses',
 'acaba',
 'academy',
 'accents',
 'accept',
 'acceptable',
 'acceptance',
 'accepting',
 'access',
 'accessible',
 'accommodate',
 'accompanies',
 'accomplish',
 'accomplished',
 'accomplishes',
 'accomplishing',
 'accomplishment',
 'account',
 'accumulates',
 'accuracy',
 'accurately',
 'accuse',
 'ace',
 'acerbic',
 'achieve',
 'achievement',
 'achievements',
 'achieves',
 'aching',
 'acid',
 'acidic',
 'acontecimentos',
 'acquainted',
 'acrid',
 'across',
 'act',
 'acted',
 'acting',
 'action',
 'actioncomedy',
 'actionoriented',
 'actionpacked',
 'actions',
 'activate',
 'actor',
 'actors',
 'actress',
 'actresses',


In [16]:
len(vectorizer.get_feature_names())

17817

### SVM Classifier

In [21]:
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix

In [15]:
classifier_linear = svm.SVC(kernel = 'linear')
classifier_linear.fit(train_vectors, train_data['Mood'])

SVC(kernel='linear')

In [16]:
predict_linear = classifier_linear.predict(test_vectors)

In [17]:
report = classification_report(test_data['Mood'], predict_linear, output_dict=True)
print('Linear SVC Positive', report['1'])
print('Linear SVC Negative', report['0'])

Linear SVC Positive {'precision': 0.7597712106768351, 'recall': 0.7379629629629629, 'f1-score': 0.7487083137623297, 'support': 1080}
Linear SVC Negative {'precision': 0.738929889298893, 'recall': 0.7606837606837606, 'f1-score': 0.7496490407112776, 'support': 1053}


In [18]:
print(confusion_matrix(test_data['Mood'], predict_linear))

[[801 252]
 [283 797]]


### Hyperparameter Tuning for SVM

In [24]:
from sklearn.model_selection import GridSearchCV

In [25]:
param_grid = {'C': np.arange(0.1,1,0.1),  
              'gamma':[0.01,0.02,0.03,0.04,0.05], 
              'kernel': ['linear','poly','rbf'],
              'degree': [2,3,4,5]} 

In [26]:
model_svm = GridSearchCV(svm.SVC(), param_grid, cv=10, scoring='accuracy', n_jobs=-1)

In [ ]:
model_svm.fit(train_vectors, train_data['Mood'])

In [ ]:
print('Best Score:', model_svm.best_score_)
print('Best Parameters:', model_svm.best_params_)
print('Best Estimator:', model_svm.best_estimator_) 

In [ ]:
predict = model_svm.predict(test_vectors)

In [ ]:
print(confusion_matrix(test_data['Mood'], predict))

### Naive Bayes Classifier

In [17]:
from sklearn.naive_bayes import MultinomialNB
model_nb = MultinomialNB()

In [18]:
model_nb.fit(train_vectors, train_data['Mood'])

MultinomialNB()

In [19]:
pred = model_nb.predict(test_vectors)

In [22]:
print(classification_report(test_data['Mood'], pred))

              precision    recall  f1-score   support

           0       0.76      0.77      0.77      1053
           1       0.78      0.77      0.77      1080

    accuracy                           0.77      2133
   macro avg       0.77      0.77      0.77      2133
weighted avg       0.77      0.77      0.77      2133



In [23]:
print(confusion_matrix(test_data['Mood'], pred))

[[816 237]
 [251 829]]
